import { GoogleGenAI, Type } from "@google/genai";
import { Boss } from "../types";

// Helper to sanitize boss data if necessary
const sanitizeBoss = (data: any, theme: string): Boss => {
  return {
    id: `gen-boss-${Date.now()}-${Math.random().toString(36).substring(2, 9)}`,
    name: data.name || "Unknown Entity",
    emoji: data.emoji || "❓",
    description: data.description || "A mysterious opponent.",
    maxHp: data.hp || 1000,
    currentHp: data.hp || 1000,
    type: 'Normal', // Defaulting to Normal as theme might not match ElementType
    skillType: 'damage_single',
    skillName: 'Generated Move',
    skillDescription: 'A move generated by AI.',
    skillCost: 15,
  };
};

export const generateBoss = async (theme: string): Promise<Boss> => {
  if (!process.env.API_KEY) {
    throw new Error("API Key is missing");
  }

  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

  try {
    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: `Create a fun, creative boss for a match-3 game based on the theme: "${theme}". 
      Return a JSON object with:
      - name: A creative name.
      - emoji: A single emoji representing the boss.
      - hp: An integer between 1000 and 5000 representing hit points.
      - description: A short, funny 1-sentence bio.
      `,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            name: { type: Type.STRING },
            emoji: { type: Type.STRING },
            hp: { type: Type.INTEGER },
            description: { type: Type.STRING },
          },
          required: ["name", "emoji", "hp", "description"],
        },
      },
    });

    const text = response.text;
    if (!text) throw new Error("No response from AI");
    
    const data = JSON.parse(text);
    return sanitizeBoss(data, theme);
  } catch (error) {
    console.error("Failed to generate boss:", error);
    // Fallback boss if AI fails
    return {
      id: `error-boss-${Date.now()}`,
      name: `Glitch-${theme}`,
      emoji: "👾",
      description: "An entity formed from API errors.",
      maxHp: 1500,
      currentHp: 1500,
      type: 'Normal',
      skillType: 'nuke',
      skillName: 'Error Beam',
      skillDescription: 'Deals damage based on bugs.',
      skillCost: 20,
    };
  }
};